default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "myapp") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_development") %>

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_production") %>
